### ISSUE TITLE
Capstone-JavaScript-project

### ISSUE THREAD

**Issue by VitorGuedesMadeira** [VitorGuedesMadeira/Capstone-Javascript#21]
### Authors(2):
- [**Vitor Guedes Madeira**](https://github.com/Vitor-Guedes-Madeira)
- [**Raul Andres Ospina**](https://github.com/raminka13/)

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
