### ISSUE TITLE
Morning session: peer-to-peer code reviews

### ISSUE THREAD

**Issue by fahimy143** [VitorGuedesMadeira/Capstone-Javascript#22]
Hi @raminka13 
Great work 🥇  your project is perfect 👌

![](https://media1.giphy.com/media/3oz8xrlxi4mm1KnE7C/giphy.gif?cid=ecf05e47x6eoc15o9ngbdpzhdmr4bug7ctkdm5j3enq32eui&rid=giphy.gif&ct=g)

### Highlights 

- Good documentation
- no linter error
- followed all requirements 
- perfect design

Cheers and happy coding 🥂 🥂

**Comment by jaferIdrees** [comment]
### Great job.
As discussed I have one recommendation for you to use the localStorage to store the Involvement API's app ID.
Good luck 🥇
